### PR TITLE
Use SHA256 for __elgg_session

### PR DESCRIPTION
**Pull request by Porthorian**
Changed md5 hash to sha256.

### CODE REVIEW

**Comment by Serkan-devel** [comment]
Who came to the idea to explicitly use md5 for hashing? It's even referenced in the whitpaper. I don't think I need to tell why md5 is insecure

**Comment by Porthorian** [comment]
I was a little surprised when, I saw that tbh. After all it is a deacentralized social network.

**Comment by markharding** [comment]
md5 is used here as it is just very lightweight unique id for the server side session. There's not security issue with using md5 here as there really aren't really any attack vectors such as brute force attacks that would really do anything.

Passwords are hashed with bcrypt.

**Comment by Serkan-devel** [comment]
Fair enough

**Comment by Porthorian** [comment]
Stale not needed

**Pull request closed without merging**
