### PR TITLE
Push msgpack implementation out of PHP userland

### PR DESCRIPTION
**Pull request by DaSourcerer**
Instead of using a userland implementation of msgpack, taking advatage of the [PHP pecl module](https://github.com/msgpack/msgpack-php) may prove to be faster and comes with a real chance of decreasing Minds' operational costs. For this to work, the `php-msgpack` package has to be installed.

Further reading: [pecl::msgpack module info](https://pecl.php.net/package/msgpack)

### CODE REVIEW

**Comment by 001101** [comment]
keep it simple stupid, nais!

**Comment by markharding** [comment]
@edgebal I recall we had problems with php's msgpack and socket.io conflict?

**Comment by DaSourcerer** [comment]
@markharding Could that be related to socketio/socket.io-redis#17?

@001101 I somewhat lost track of Yii2 after PHP stopped being my bread and butter. But I still remember some of the contributors of that project.

**Comment by 001101** [comment]
@DaSourcerer It is very nais and evolving very much, big potential, you should give it a try. What is now your bread and butter?

**Comment by edgebal** [comment]
@markharding We had a versioning issue. There was some kind of incompatibility with the MsgPack, Socket.IO and Redis versions Minds was using. Anyhow, I think it's worth checking it out.

cc/ @DaSourcerer

**Comment by DaSourcerer** [comment]
@edgebal IIRC the PECL extension is following a newer spec for MsgPack than socket.io. Per the issue I linked, I think this can be addressed by upgrading the affected lib.

Also: No need to cc me when I opened the PR ;)

**Comment by DaSourcerer** [comment]
Ah, there's another caveat: [`msgpack.php_only`](https://github.com/msgpack/msgpack-php/blob/d30b2e581868b5fada1795972e8f4f41d58474fe/ChangeLog#L70) is set to On by default. If I see correctly, this controls how PHP objects are serialized. Switching it to Off should prevent interoperability issues.

**Comment by markharding** [comment]
We had to do this polyfill due to issues with the libraries, which I dont think are fixed yet. I'm tempted to suggest that if this isn't broken, then lets not fix it.

**Pull request closed without merging**
